---
title: "Maternity Leave in NYC"
authors: Amanda, Meghan, Akanksha, & Karina
date: November 5, 2020
output: github_document
---

Contributors: Amanda Warnock (aw3251), Meghan Bellerose (meb2308), Akanksha Nalatwad (asn2139), & Karina Myers (km3529) 


The tentative project title: Exploring Maternity Leave in NYC

**The motivation for this project:** There are many socioeconomic disparities related to maternal health outcomes (CDC, 2020). A piece of this problem is the unequal access maternity leave. We want to explore elements related to maternity leave within New York City. In this project, we will explore racial, economic, and geographic differences in maternity leave behaviors. 

**The intended final products:** We intend to create a map showing average maternity leave by zipcode, a plotly showing differences in maternity leave by ethnicity/race, a scatter plot of maternity leave by income level, a comparison of depression, welfare, and income before and after childbirth. 

**The anticipated data sources:** We intend to use data from the NYC Work and Family Leave Survey (WFLS). It was a telephone survey conducted in March of 2016 about New York City residents who gave birth in 2014. The goal was to understand the availability and accessibility of paid family leave to working parents. The WLFS also sought to describe the role that paid family leave policies play in achieving health equity for parents and children. The data is located [here](https://data.cityofnewyork.us/Health/New-York-City-Work-and-Family-Leave-Survey-WFLS-20/grnn-mvqe). Information on this survey can be found [here](https://www1.nyc.gov/assets/doh/downloads/pdf/hca/paid-family-leave-report1.pdf). 

**The planned analyses / visualizations / coding challenges:** There are many variables in this data and we plan to their names more intuitively. Additionally, we will filter for variables of interest and exclude missing data. We anticipate challenges in building a leaflet map. We also anticipate challenges since categorization of income data is limited in the main datasource. We may need to find supplemental data using census.gov. 


**Planned Timeline**

  * 11/10: light lit-review and finalize variables of interest
  * 11/12: finalize and clean dataset
  * 11/19: draft of each plot so we can get feedback at our weekly group meeting
  * 12/1: finalize plots, work on webpage and screencast


Source: 
https://www.cdc.gov/media/releases/2019/p0905-racial-ethnic-disparities-pregnancy-deaths.html
