---
title: "Paid Leave Predictor"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    runtime: shiny
---

This won't run until we add a website with something like this syntax in the site_yml, but I made a dummy website to test some of it:

  right:
    - text: "Report"
      href: project_report.html
    - text: "Paid Leave Predictor"
      href: shiny_charts.html

```{r, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
library(shiny)

charts_df = 
  read_csv("./data/merged_wfls.csv") %>% 
  drop_na(leave_type)
```

```{r}
borough_choices = 
  charts_df %>% 
  pull(borough) %>%  
  unique()

selectInput(
  "borough_choice",
  h3("Borough Choice"),
  choices = borough_choices,
  selected = "Manhattan"
)

type = charts_df %>% 
  pull(leave_type) %>% unique()

radioButtons(
  "type",
  h3("Type of Leave"),
  choices = type,
  selected = NULL)
  
sliderInput(
  "income",
  h3("Family Income"),
  0,100000,
  value = c(0,100000))

race = charts_df %>% 
  pull(race) %>% unique()

radioButtons(
  "race",
  h3("Race"),
  choices = race,
  selected = NULL
  )

  
```